// <auto-generated />
using System;
using Digesto.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Digesto.Infrastructure.Migrations
{
    [DbContext(typeof(DigestoDbContext))]
    partial class DigestoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Digesto.Domain.Entidades.Auditoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("accion");

                    b.Property<string>("Antes")
                        .HasColumnType("text")
                        .HasColumnName("antes");

                    b.Property<string>("Despues")
                        .HasColumnType("text")
                        .HasColumnName("despues");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entidad");

                    b.Property<string>("EntidadId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entidad_id");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("usuario");

                    b.HasKey("Id")
                        .HasName("pk_auditoria");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("ix_auditoria_fecha");

                    b.HasIndex("Entidad", "EntidadId")
                        .HasDatabaseName("ix_auditoria_entidad");

                    b.ToTable("auditoria", (string)null);
                });

            modelBuilder.Entity("Digesto.Domain.Entidades.Boletin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("ArchivoId")
                        .HasColumnType("uuid")
                        .HasColumnName("archivo_id");

                    b.Property<DateOnly>("FechaPublicacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_publicacion");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.HasKey("Id")
                        .HasName("pk_boletin");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("ix_boletin_numero");

                    b.ToTable("boletin", (string)null);
                });

            modelBuilder.Entity("Digesto.Domain.Entidades.ConsultaBusqueda", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Filtros")
                        .HasColumnType("text")
                        .HasColumnName("filtros");

                    b.Property<int>("Ms")
                        .HasColumnType("integer")
                        .HasColumnName("ms");

                    b.Property<string>("Q")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("q");

                    b.Property<int>("Total")
                        .HasColumnType("integer")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("pk_consulta_busqueda");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("ix_consulta_busqueda_fecha");

                    b.ToTable("consulta_busqueda", (string)null);
                });

            modelBuilder.Entity("Digesto.Domain.Entidades.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<int?>("PadreId")
                        .HasColumnType("integer")
                        .HasColumnName("padre_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_materia");

                    b.HasIndex("PadreId")
                        .HasDatabaseName("ix_materia_padre_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_materia_slug");

                    b.ToTable("materia", (string)null);
                });

            modelBuilder.Entity("Digesto.Domain.Entidades.Norma", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("ActualizadoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actualizado_por");

                    b.Property<short>("Anio")
                        .HasColumnType("smallint")
                        .HasColumnName("anio");

                    b.Property<int?>("BoletinId")
                        .HasColumnType("integer")
                        .HasColumnName("boletin_id");

                    b.Property<decimal?>("CalidadOcr")
                        .HasColumnType("numeric")
                        .HasColumnName("calidad_ocr");

                    b.Property<string>("CodigoNormalizado")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("codigo_normalizado");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("creado_por");

                    b.Property<int>("EstadoPublicacion")
                        .HasColumnType("integer")
                        .HasColumnName("estado_publicacion");

                    b.Property<string>("Expediente")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("expediente");

                    b.Property<DateOnly?>("FechaPublicacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_publicacion");

                    b.Property<DateOnly>("FechaSancion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_sancion");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<int>("OrganoEmisorId")
                        .HasColumnType("integer")
                        .HasColumnName("organo_emisor_id");

                    b.Property<string[]>("PalabrasClave")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("palabras_clave");

                    b.Property<string>("Resumen")
                        .HasColumnType("text")
                        .HasColumnName("resumen");

                    b.Property<string>("Sufijo")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("sufijo");

                    b.Property<int>("TextoOrigen")
                        .HasColumnType("integer")
                        .HasColumnName("texto_origen");

                    b.Property<int>("TipoNormaId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_norma_id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("titulo");

                    b.Property<int>("Vigencia")
                        .HasColumnType("integer")
                        .HasColumnName("vigencia");

                    b.Property<int>("Visibilidad")
                        .HasColumnType("integer")
                        .HasColumnName("visibilidad");

                    b.HasKey("Id")
                        .HasName("pk_norma");

                    b.HasIndex("BoletinId")
                        .HasDatabaseName("ix_norma_boletin_id");

                    b.HasIndex("CodigoNormalizado")
                        .IsUnique()
                        .HasDatabaseName("ix_norma_codigo_normalizado");

                    b.HasIndex("EstadoPublicacion")
                        .HasDatabaseName("ix_norma_estado_publicacion");

                    b.HasIndex("FechaSancion")
                        .HasDatabaseName("ix_norma_fecha_sancion");

                    b.HasIndex("OrganoEmisorId")
                        .HasDatabaseName("ix_norma_organo_emisor_id");

                    b.HasIndex("TipoNormaId")
                        .HasDatabaseName("ix_norma_tipo_norma_id");

                    b.HasIndex("Visibilidad")
                        .HasDatabaseName("ix_norma_visibilidad");

                    b.HasIndex("Anio", "Numero")
                        .HasDatabaseName("ix_norma_anio_numero");

                    b.ToTable("norma", (string)null);
                });

            modelBuilder.Entity("Digesto.Domain.Entidades.NormaArchivo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("Bytes")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes");

                    b.Property<string>("FirmaDigital")
                        .HasColumnType("text")
                        .HasColumnName("firma_digital");

                    b.Property<string>("Mime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mime");

                    b.Property<string>("NombreOriginal")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("nombre_original");

                    b.Property<Guid>("NormaId")
                        .HasColumnType("uuid")
                        .HasColumnName("norma_id");

                    b.Property<int>("Paginas")
                        .HasColumnType("integer")
                        .HasColumnName("paginas");

                    b.Property<int>("Rol")
                        .HasColumnType("integer")
                        .HasColumnName("rol");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("storage_key");

                    b.HasKey("Id")
                        .HasName("pk_norma_archivo");

                    b.HasIndex("NormaId")
                        .HasDatabaseName("ix_norma_archivo_norma_id");

                    b.HasIndex("Sha256")
                        .HasDatabaseName("ix_norma_archivo_sha256");

                    b.ToTable("norma_archivo", (string)null);
                });

            modelBuilder.Entity("Digesto.Domain.Entidades.NormaFragmento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Etiqueta")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("etiqueta");

                    b.Property<string>("Html")
                        .HasColumnType("text")
                        .HasColumnName("html");

                    b.Property<Guid>("NormaId")
                        .HasColumnType("uuid")
                        .HasColumnName("norma_id");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<int?>("PaginaDesde")
                        .HasColumnType("integer")
                        .HasColumnName("pagina_desde");

                    b.Property<int?>("PaginaHasta")
                        .HasColumnType("integer")
                        .HasColumnName("pagina_hasta");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("texto");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_norma_fragmento");

                    b.HasIndex("NormaId", "Orden")
                        .HasDatabaseName("ix_fragmento_norma");

                    b.ToTable("norma_fragmento", (string)null);
                });

            modelBuilder.Entity("Digesto.Domain.Entidades.NormaMateria", b =>
                {
                    b.Property<Guid>("NormaId")
                        .HasColumnType("uuid")
                        .HasColumnName("norma_id");

                    b.Property<int>("MateriaId")
                        .HasColumnType("integer")
                        .HasColumnName("materia_id");

                    b.HasKey("NormaId", "MateriaId")
                        .HasName("pk_norma_materia");

                    b.HasIndex("MateriaId")
                        .HasDatabaseName("ix_norma_materia_materia_id");

                    b.ToTable("norma_materia", (string)null);
                });

            modelBuilder.Entity("Digesto.Domain.Entidades.NormaRelacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Detalle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("detalle");

                    b.Property<Guid>("NormaDestinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("norma_destino_id");

                    b.Property<Guid>("NormaOrigenId")
                        .HasColumnType("uuid")
                        .HasColumnName("norma_origen_id");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_norma_relacion");

                    b.HasIndex("NormaDestinoId")
                        .HasDatabaseName("ix_norma_relacion_norma_destino_id");

                    b.HasIndex("NormaOrigenId", "NormaDestinoId", "Tipo")
                        .IsUnique()
                        .HasDatabaseName("ix_norma_relacion_unica");

                    b.ToTable("norma_relacion", (string)null);
                });

            modelBuilder.Entity("Digesto.Domain.Entidades.OrganoEmisor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<int?>("PadreId")
                        .HasColumnType("integer")
                        .HasColumnName("padre_id");

                    b.HasKey("Id")
                        .HasName("pk_organo_emisor");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_organo_emisor_codigo");

                    b.HasIndex("PadreId")
                        .HasDatabaseName("ix_organo_emisor_padre_id");

                    b.ToTable("organo_emisor", (string)null);
                });

            modelBuilder.Entity("Digesto.Domain.Entidades.ProcesoIngesta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ArchivoId")
                        .HasColumnType("uuid")
                        .HasColumnName("archivo_id");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<string>("Etapa")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("etapa");

                    b.Property<int>("Intentos")
                        .HasColumnType("integer")
                        .HasColumnName("intentos");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_at");

                    b.Property<Guid>("NormaId")
                        .HasColumnType("uuid")
                        .HasColumnName("norma_id");

                    b.HasKey("Id")
                        .HasName("pk_proceso_ingesta");

                    b.HasIndex("ArchivoId")
                        .HasDatabaseName("ix_proceso_ingesta_archivo_id");

                    b.HasIndex("NormaId")
                        .HasDatabaseName("ix_proceso_ingesta_norma_id");

                    b.HasIndex("Estado", "Id")
                        .HasDatabaseName("ix_proceso_ingesta_cola");

                    b.ToTable("proceso_ingesta", (string)null);
                });

            modelBuilder.Entity("Digesto.Domain.Entidades.TipoNorma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Alcance")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("alcance");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_tipo_norma");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_tipo_norma_codigo");

                    b.ToTable("tipo_norma", (string)null);
                });

            modelBuilder.Entity("Digesto.Infrastructure.Persistencia.UsuarioApp", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_roles_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_roles_claims_role_id");

                    b.ToTable("roles_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_usuarios_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_usuarios_claims_user_id");

                    b.ToTable("usuarios_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_usuarios_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_usuarios_logins_user_id");

                    b.ToTable("usuarios_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_usuarios_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_usuarios_roles_role_id");

                    b.ToTable("usuarios_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_usuarios_tokens");

                    b.ToTable("usuarios_tokens", (string)null);
                });

            modelBuilder.Entity("Digesto.Domain.Entidades.Materia", b =>
                {
                    b.HasOne("Digesto.Domain.Entidades.Materia", "Padre")
                        .WithMany("Hijas")
                        .HasForeignKey("PadreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_materia_materia_padre_id");

                    b.Navigation("Padre");
                });

            modelBuilder.Entity("Digesto.Domain.Entidades.Norma", b =>
                {
                    b.HasOne("Digesto.Domain.Entidades.Boletin", "Boletin")
                        .WithMany("Normas")
                        .HasForeignKey("BoletinId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_norma_boletin_boletin_id");

                    b.HasOne("Digesto.Domain.Entidades.OrganoEmisor", "OrganoEmisor")
                        .WithMany("Normas")
                        .HasForeignKey("OrganoEmisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_norma_organos_emisores_organo_emisor_id");

                    b.HasOne("Digesto.Domain.Entidades.TipoNorma", "TipoNorma")
                        .WithMany("Normas")
                        .HasForeignKey("TipoNormaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_norma_tipos_norma_tipo_norma_id");

                    b.Navigation("Boletin");

                    b.Navigation("OrganoEmisor");

                    b.Navigation("TipoNorma");
                });

            modelBuilder.Entity("Digesto.Domain.Entidades.NormaArchivo", b =>
                {
                    b.HasOne("Digesto.Domain.Entidades.Norma", "Norma")
                        .WithMany("Archivos")
                        .HasForeignKey("NormaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_norma_archivo_normas_norma_id");

                    b.Navigation("Norma");
                });

            modelBuilder.Entity("Digesto.Domain.Entidades.NormaFragmento", b =>
                {
                    b.HasOne("Digesto.Domain.Entidades.Norma", "Norma")
                        .WithMany("Fragmentos")
                        .HasForeignKey("NormaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_norma_fragmento_norma_norma_id");

                    b.Navigation("Norma");
                });

            modelBuilder.Entity("Digesto.Domain.Entidades.NormaMateria", b =>
                {
                    b.HasOne("Digesto.Domain.Entidades.Materia", "Materia")
                        .WithMany("Normas")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_norma_materia_materias_materia_id");

                    b.HasOne("Digesto.Domain.Entidades.Norma", "Norma")
                        .WithMany("Materias")
                        .HasForeignKey("NormaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_norma_materia_normas_norma_id");

                    b.Navigation("Materia");

                    b.Navigation("Norma");
                });

            modelBuilder.Entity("Digesto.Domain.Entidades.NormaRelacion", b =>
                {
                    b.HasOne("Digesto.Domain.Entidades.Norma", "NormaDestino")
                        .WithMany()
                        .HasForeignKey("NormaDestinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_norma_relacion_norma_norma_destino_id");

                    b.HasOne("Digesto.Domain.Entidades.Norma", "NormaOrigen")
                        .WithMany()
                        .HasForeignKey("NormaOrigenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_norma_relacion_norma_norma_origen_id");

                    b.Navigation("NormaDestino");

                    b.Navigation("NormaOrigen");
                });

            modelBuilder.Entity("Digesto.Domain.Entidades.OrganoEmisor", b =>
                {
                    b.HasOne("Digesto.Domain.Entidades.OrganoEmisor", "Padre")
                        .WithMany("Hijos")
                        .HasForeignKey("PadreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_organo_emisor_organo_emisor_padre_id");

                    b.Navigation("Padre");
                });

            modelBuilder.Entity("Digesto.Domain.Entidades.ProcesoIngesta", b =>
                {
                    b.HasOne("Digesto.Domain.Entidades.NormaArchivo", "Archivo")
                        .WithMany()
                        .HasForeignKey("ArchivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_proceso_ingesta_norma_archivo_archivo_id");

                    b.HasOne("Digesto.Domain.Entidades.Norma", "Norma")
                        .WithMany()
                        .HasForeignKey("NormaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_proceso_ingesta_norma_norma_id");

                    b.Navigation("Archivo");

                    b.Navigation("Norma");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roles_claims_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Digesto.Infrastructure.Persistencia.UsuarioApp", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_claims_usuarios_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Digesto.Infrastructure.Persistencia.UsuarioApp", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_logins_usuarios_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_roles_roles_role_id");

                    b.HasOne("Digesto.Infrastructure.Persistencia.UsuarioApp", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_roles_usuarios_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Digesto.Infrastructure.Persistencia.UsuarioApp", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_tokens_usuarios_user_id");
                });

            modelBuilder.Entity("Digesto.Domain.Entidades.Boletin", b =>
                {
                    b.Navigation("Normas");
                });

            modelBuilder.Entity("Digesto.Domain.Entidades.Materia", b =>
                {
                    b.Navigation("Hijas");

                    b.Navigation("Normas");
                });

            modelBuilder.Entity("Digesto.Domain.Entidades.Norma", b =>
                {
                    b.Navigation("Archivos");

                    b.Navigation("Fragmentos");

                    b.Navigation("Materias");
                });

            modelBuilder.Entity("Digesto.Domain.Entidades.OrganoEmisor", b =>
                {
                    b.Navigation("Hijos");

                    b.Navigation("Normas");
                });

            modelBuilder.Entity("Digesto.Domain.Entidades.TipoNorma", b =>
                {
                    b.Navigation("Normas");
                });
#pragma warning restore 612, 618
        }
    }
}
